language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# command to run tests
install:
  - pip install -q tensorflow
script:
  - python --version
  - python -m unittest discover -s tests -p testDQN.py
