sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
  - env:
    - DOCKER_JOB_NAME='tensorforce_pytest_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:latest'
  - env:
    - DOCKER_JOB_NAME='tensorforce_pytest_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:latest-py3'

before_install:
  - docker pull ${DOCKER_IMAGE}
  - docker run -d --rm --name ${DOCKER_JOB_NAME} -v $(pwd):/roomai ${DOCKER_IMAGE} /bin/bash -c 'while true; do sleep 1; done';

install:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'python -m pip install -U pip';
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /roomai && python -m pip install .';

script:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /roomai && python -m discover -s tests';

notifications:
  email:
    recipients:
      - lili1987mail@gmai.com
    on_success: never
    on_failure: always

